// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNutritionComrade.Infrastructure.Data;

namespace MyNutritionComrade.Infrastructure.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200328090518_ConsumedProduct")]
    partial class ConsumedProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyNutritionComrade.Core.Domain.Entities.ConsumedProduct", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "Day", "Time", "ProductId");

                    b.ToTable("ConsumedProduct");
                });

            modelBuilder.Entity("MyNutritionComrade.Core.Domain.Entities.ConsumedProduct", b =>
                {
                    b.OwnsOne("MyNutritionComrade.Core.Domain.NutritionInformation", "NutritionInformation", b1 =>
                        {
                            b1.Property<string>("ConsumedProductUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("ConsumedProductDay")
                                .HasColumnType("datetime2");

                            b1.Property<int>("ConsumedProductTime")
                                .HasColumnType("int");

                            b1.Property<string>("ConsumedProductProductId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Carbohydrates")
                                .HasColumnType("float");

                            b1.Property<double>("DietaryFiber")
                                .HasColumnType("float");

                            b1.Property<double>("Energy")
                                .HasColumnType("float");

                            b1.Property<double>("Fat")
                                .HasColumnType("float");

                            b1.Property<double>("Mass")
                                .HasColumnType("float");

                            b1.Property<double>("Protein")
                                .HasColumnType("float");

                            b1.Property<double>("SaturatedFat")
                                .HasColumnType("float");

                            b1.Property<double>("Sodium")
                                .HasColumnType("float");

                            b1.Property<double>("Sugars")
                                .HasColumnType("float");

                            b1.HasKey("ConsumedProductUserId", "ConsumedProductDay", "ConsumedProductTime", "ConsumedProductProductId");

                            b1.ToTable("ConsumedProduct");

                            b1.WithOwner()
                                .HasForeignKey("ConsumedProductUserId", "ConsumedProductDay", "ConsumedProductTime", "ConsumedProductProductId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
