version: "3.4"

services:
  community-catalog:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mynutritioncomrade.rule=Host(`nutritions.${SITE_HOST}`)"
      - "traefik.http.routers.mynutritioncomrade.entrypoints=websecure"
      - "traefik.http.routers.mynutritioncomrade.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.mynutritioncomrade.tls=true"
      - "traefik.http.services.community-catalog.loadbalancer.healthcheck.path=/health/ready"
