version: "3.4"

services:
  mongo:
    image: mongo
    command: "--replSet rs0"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s

  community-catalog:
    image: ${DOCKER_REGISTRY-}community-catalog
    build:
      context: .
      dockerfile: Services/CommunityCatalog/CommunityCatalog/Dockerfile
    environment:
      - MongoDb__ConnectionString=mongodb://mongo
      - AuthSettings__SecretKey=${AUTH_SECRET_KEY}
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT}
      - IdentityOptions__SecretKey=${AUTH_SECRET_KEY}
      - IdentityOptions__EmailSalt=${EMAIL_SALT}
    depends_on:
      - mongo
