name: ASP.NET Core
on:
  push:
    paths:
      - src/**
      - .github/workflows/asp-net-core-test.yml
      - "!src/Mobile/**"

  pull_request:
    branches:
      - develop
    paths:
      - src/**
      - .github/workflows/asp-net-core-test.yml
      - "!src/Mobile/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore MyNutritionComrade.sln
      - name: Test
        run: dotnet test MyNutritionComrade.sln --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      - uses: codecov/codecov-action@v1
