name: Expo Publish

on:
  push:
    branches: [prod-expo]
    paths:
      - react-native/**
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    env:
      working-directory: ./react-native
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: 'echo "$ENV_INFO" > ./src/env.ts'
        shell: bash
        working-directory: ${{ env.working-directory }}
        env:
          ENV_INFO: ${{secrets.ENV_INFO}}
      - run: yarn install
        working-directory: ${{ env.working-directory }}
      - run: expo publish
        working-directory: ${{ env.working-directory }}
