name: Deploy server
on:
  push:
    branches:
      - prod-server

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish
        run: dotnet publish -c Release --no-restore --output ./deployment ./src/MyNutritionComrade
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }} # https://github.com/marketplace/actions/webfactory-ssh-agent
      - name: Add remote to known hosts
        run: ssh-keyscan "$PROD_HOST" >> ~/.ssh/known_hosts
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
      - name: Clone production repository
        shell: bash
        env:
          GIT_REMOTE_URL: ${{ secrets.PROD_GIT_REMOTE_URL }}
        run: git clone --bare "$GIT_REMOTE_URL" deployment.git
      - name: Deploy to production server
        working-directory: deployment.git
        run: |
          git config --global user.email "anapher@protonmail.com"
          git config --global user.name "GitHub Action"
          git --work-tree ../deployment add -A
          git --work-tree ../deployment commit -m "Run no. $GITHUB_RUN_NUMBER ($GITHUB_SHA)"
          git push origin master
